[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/auth/callback"
  to = "/.netlify/functions/auth" # Points to your serverless function
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
