[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Redirect all unmatched routes to index.html (for React client-side routing)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
