[build]
  command = "npm run build"
  publish = "dist" # Adjust if needed
  functions = "netlify/functions"

[[redirects]]
  from = "/auth/callback"
  to = "https://githuberist.netlify.app/auth/callback" # Or the correct path in your app
  status = 200
